### ISSUE TITLE
Command pipe ssh doesn't work

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1131] opened 2020-05-22 13:32 UTC
**Describe the bug**
Command pipe ssh doesn't work in pipe CLI for Windows

**To Reproduce**
Install CLI for Windows. Perform the CLI pipe ssh command, e.g.:
    pipe ssh <RUN_ID>

**Actual behavior**
Error:
`Error: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xfc in position 3: invalid start byte`

**Expected behavior**
An interactive session should start over the running instance with the specified Run ID using the SSH protocol.

**Environment:**
- Cloud Provider: N/A
- Version 0.16.0.5454

**Comment by sidoruka** [comment] 2020-05-22 13:34
@maryvictol  Is it a duplicate of #899 or something different?

**Comment by NShaforostov** [comment] 2020-05-22 13:35
It's a duplicate of #899

**Closed as completed by NShaforostov** 2020-05-22 13:35 UTC
Labels: kind/bug, kind/duplicate
