### ISSUE TITLE
Tool configuration shall allow to restrict execution in a specific cloud region

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1035] opened 2020-04-06 19:14 UTC
**Background**
At the moment, Cloud Pipeline allows to select a cloud region for a particular job execution (in a `Launch Form`), but a tool/version itself does not have any link with a region.
In certain cases, we'd like to enforce users to run some tools in a specific cloud region.

**Approach**
* Cloud Region configuration shall be added to the tool configuration:
  * API (if not yet)
  * GUI
* This configuration parameter shall allow `Not configured` value (a default one), which shall make a tool behave as now: not preference - all the available regions can be used
* If a user does not have an access to the region, which is enforced for a tools - we shall restrict running such a tool
* This shall be handled for all the forms in the GUI: a tool's region shall be set as a default on in the  `Launch Form(s)`

**Comment by sidoruka** [comment] 2020-04-06 19:14
As usual - let's start from the API part and pass it to @rodichenko

**Comment by mzueva** [comment] 2020-04-09 13:28
@rodichenko server side is merged

**Comment by rodichenko** [comment] 2020-04-10 09:54
@NShaforostov could you verify this issue please?

**Comment by NShaforostov** [comment] 2020-04-13 09:42
@rodichenko, I've tried to verify this feature. Some notes:
1. If a user does not have access to the region, which is enforced for a tool, and he tries to launch it with default settings - the system restricts running such a tool as expected. But if the user tries to launch such a tool with **custom settings** (even doing no changes) - the run is being launched with no errors.
2. If a user does not have access to the region, which is enforced for a tool, and he tries to launch it with default settings - the system restricts running such a tool with the following message, e.g.: `Tool is allowed to be executed only in '6' cloud region. Required '1' cloud region is not allowed for the tool execution.` Could we display Region names instead of their IDs?
3. If a user does not have access to the region, which is enforced for a tool - in all forms (`Launch`, `Tool/Version settings` and other) these regions are displayed in disabled fields as region IDs, not names - could we display their names?
4. If a user does not have access to the region, which is enforced for a tool, and he tries to launch a **pipeline** using that tool as an image - the region field also is disabled, the region is displayed as ID, but the run is being launched with no errors.
5. The same as in item 4 is rightly for a **detached configuration**.

**Comment by rodichenko** [comment] 2020-04-13 13:02
@NShaforostov we added **Cloud Region not available** warning for such situations;
@mzueva could you handle 2) part? As for the 4) part - we have an issue for that (#1042)

**Comment by tcibinan** [comment] 2020-04-13 14:03
@NShaforostov 2) is resolved via b581a07ba7a089ca8004e81a55e3a08b7796110d.

**Comment by NShaforostov** [comment] 2020-04-14 07:14
@rodichenko @tcibinan 
Currently, if a user does not have access to the region, which is enforced for a tool, and he tries to launch it with **any** settings (default/custom) - the system displays the message before the run:
![image](https://user-images.githubusercontent.com/45459424/79196217-4f2f7500-7e38-11ea-9bd9-330a1895615b.png)
But in **any** case, it doesn't restrict the launch - a user can click the "Launch" button and the run will be started normally.

**Comment by rodichenko** [comment] 2020-04-14 07:39
@NShaforostov the second part

> If a user does not have access to the region, which is enforced for a tool, and he tries to launch it with default settings - the system restricts running such a tool with the following message, e.g.: Tool is allowed to be executed only in '6' cloud region. Required '1' cloud region is not allowed for the tool execution. Could we display Region names instead of their IDs?

is related to the direct API calls, because user is unable to set another region for such tool during launch stage via GUI (`Cloud region` option is read-only in such case).

As for the 4 and 5 parts
>4. If a user does not have access to the region, which is enforced for a tool, and he tries to launch a pipeline using that tool as an image - the region field also is disabled, the region is displayed as ID, but the run is being launched with no errors.
>5. The same as in item 4 is rightly for a detached configuration.

as I understand, it is still in progress (#1042). GUI will display an error message (e.g. `Cloud region is not available`) if user clicks the `Launch` button

**Comment by mzueva** [comment] 2020-04-15 12:40
@NShaforostov #1042 is fixed, please take a look

**Comment by NShaforostov** [comment] 2020-04-15 15:45
@mzueva, I've taken a look.
Currently, the feature works nicely for general users.
But now a new issue has appeared:
If the region is forcibly configured for the tool and the admin or its role aren't specified for that region (in the cloud region preferences) - admin can't launch the tool in this case.

**Comment by tcibinan** [comment] 2020-04-15 17:07
Thanks @NShaforostov. The issue should be fixed after f4731ec3c954b982bddeaf56f12a7f2a4f9c4731. From now on admins are allowed to run instances in any cloud region despite tool region restrictions.

**Comment by NShaforostov** [comment] 2020-04-15 20:54
@tcibinan, thanks. Verified, now works correctly.
@rodichenko, I hope, it'll be the last minor note for that issue:
1. The user does not have access to the region, which is enforced for a specific tool version
2. He tries to launch that tool version with custom settings
3. At the Launch form, the user selects another Docker image/version that hasn't region restrictions
4. In the "Cloud Region" field of the Launch form, the region ID is being displayed instead of the "Not available" item
A described note belongs to the Tool launch form only, for the Pipeline/Configuration all work well.

**Comment by rodichenko** [comment] 2020-04-16 07:14
@NShaforostov sure, no problem! f304e1ddcb1a2b423380d98e9e33264b343bc653 should fix that

**Comment by NShaforostov** [comment] 2020-04-16 09:05
@rodichenko @mzueva @tcibinan 
Finally, all work well. Thanks!

**Comment by maryvictol** [comment] 2020-05-15 11:37
@rodichenko 
If specify the Cloud Region that belongs to another Cloud Provider, select Instance type for it and then return initial Cloud Region, then selected instance type for another Cloud Provider remains in the field.

**To Reproduce**
Steps to reproduce the behavior:
1. Open the tool settings
2. Set the Cloud Region different from the current one >> "Instance type" field is cleaned
3. Select "Instance types" from dropdown list values for selected Cloud Region
![image](https://user-images.githubusercontent.com/47791878/82045561-f7df2780-96b7-11ea-89f2-548849a02cbe.png)
4. Return initial Cloud Region

Exp.: Instance type is empty
Act.: Selected instance type for another Cloud Provider remains in the field. 'Save' button is active so user can save Execution environment without Instance type as result.
![image](https://user-images.githubusercontent.com/47791878/82046307-4f31c780-96b9-11ea-9e51-5b5e07f25be1.png)

**Comment by rodichenko** [comment] 2020-05-15 15:18
@maryvictol should be fixed via f62041519016246264634aef3b8ca38785c44a75, could you verify this please?

**Comment by NShaforostov** [comment] 2020-07-04 12:50
Docs were updated via #1184

**Comment by maryvictol** [comment] 2020-07-06 10:51
> @maryvictol should be fixed via [f620415](https://github.com/epam/cloud-pipeline/commit/f62041519016246264634aef3b8ca38785c44a75), could you verify this please

Verified on Version 0.16.0.5714

**Closed as completed** 2020-08-17 18:05 UTC
Labels: kind/enhancement, sys/registry, sys/core, state/verify, goal/dorado :sparkles:
