### ISSUE TITLE
Auto-scaled cluster is not started: Fail to install SGE worker

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1205] opened 2020-07-06 22:48 UTC
**Describe the bug**
Auto-scaled cluster is not started. **SGEMasterSetup** run task hangs with the following message: `Fail to install SGE worker`

**To Reproduce**

1. Open library
2. Create pipeline (from SHELL template)
3. Open created pipeline
4. Click "RUN" button
5. In an appeared page click on "Advanced"
6. Input valid values into the fields "Node type", "Disk (Gb)"
7. Set as "Cmd template" next command:

`qsub -b y -e /common/workdir/err -o /common/workdir/out -t 1:10 sleep 1d && sleep infinity`

8. Click on "Configure cluster"
9. Click on "Auto-scaled cluster"
10. Specify "1" into "Auto-scaled up to:" field
11. Click OK
12. Click "Launch" button
14. In an appeared pop-up window click "Launch" button

**Expected behavior**
In a few minutes, one child node is started. On "ACTIVE RUNS" tab in front of the previously-started run name "+" button appears. Child pipeline is being displayed by click on "+" button, this child pipeline has the number in "Parent run" field that is equal to the parent-run ID

**Screenshots**
![Autoscaling](https://user-images.githubusercontent.com/47791878/86660868-cddd1e00-bff3-11ea-84e0-469e49010135.png)

**Environment:**
 - Cloud Provider: AWS, Azure
 - Version 0.16.0.5943
 - Browser: chrome

**Comment by tcibinan** [comment] 2020-07-07 10:45
The issue is caused by the changes introduced in 39839b4f6805a21fc6c4b56c15539c5b88c8112c. It affects SGE installation on centos images and LFS installation on ubuntu distributions.

**Comment by tcibinan** [comment] 2020-07-22 09:31
@maryvictol Should be fixed by 0c1149168f6f3c9e9f4ea532d25b7aeb78b948c0 for now. Could you please verify?

**Comment by maryvictol** [comment] 2020-07-22 09:36
Verified on Version: 0.17.0.6141

**Comment by maryvictol** [comment] 2020-07-22 09:40
Closed as fixed

**Closed as completed** 2020-07-22 09:40 UTC
Labels: kind/bug, state/verify
