### ISSUE TITLE
User shall be able to create "symlinks" for the tools in the registry

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1095] opened 2020-05-08 09:02 UTC
**Background**
A clear and concise description of what the problem is. Ex. At the moment, Cloud Pipeline does not allow [...] and it would be nice to [...] because [...]

**Approach**

**Other options**

**Comment by tcibinan** [comment] 2020-05-26 12:43
Duplicate of #1122.

**Closed as completed by tcibinan** 2020-05-26 12:43 UTC
Labels: kind/duplicate, kind/enhancement, sys/registry, state/draft
